### ISSUE TITLE
Problem when loading pseudo element css selectors for both Chrome and FF

### ISSUE THREAD

**Issue by edzillion** [edzillion/blood-n-guts#170]
```css
::-moz-color-swatch {
  opacity: 1;
}

::-webkit-color-swatch {
  opacity: 1;
}
```

Seems to depend on the load order, but each browser seems to stop the other from loading their own rule.
